/* @bruin
name: lineage_demo.orders_enriched
type: bq.sql
description: Orders joined with customer info — fan-in of stg_orders and stg_customers.
materialization:
  type: table
depends:
  - lineage_demo.stg_orders
  - lineage_demo.stg_customers
  - uri: bigquery://bruin-playground-bensu.cloud_test.raw_events
columns:
  - name: order_id
    type: integer
    description: Unique identifier for the order.
    primary_key: true
    checks:
      - name: not_null
      - name: unique
  - name: customer_id
    type: integer
    description: Identifier of the customer who placed the order.
    checks:
      - name: not_null
  - name: name
    type: string
    description: Customer display name.
    checks:
      - name: not_null
  - name: region
    type: string
    description: Customer region.
    checks:
      - name: accepted_values
        value: ["EU", "US"]
  - name: amount
    type: integer
    description: Order amount.
    checks:
      - name: non_negative
  - name: order_date
    type: date
    description: Date the order was placed.
    checks:
      - name: not_null
custom_checks:
  - name: row_count_matches_raw_orders
    description: Enriched orders should match the 20 rows generated by raw_orders.
    value: 20
    query: SELECT COUNT(*) FROM lineage_demo.orders_enriched
tags:
  - mart
@bruin */

SELECT
    o.order_id,
    o.customer_id,
    c.name,
    c.region,
    o.amount,
    o.order_date
FROM lineage_demo.stg_orders o
JOIN lineage_demo.stg_customers c USING (customer_id)
