name: "{{ var.client }}_pipe"
schedule: "{{ var.schedule }}"

variables:
  client:
    type: string
    default: default_client
  region:
    type: string
    default: us
  schedule:
    type: string
    default: "@daily"

variants:
  client_alpha:
    client: alpha_wrong
    region: 1234
    schedule: "@hourly"
    wrong_field: "This field is not defined in the variables section"